website/auth.py
from flask import Blueprint, redirect, render_template, request, flash, url_for
from .controlers.usercontroler import *
from .controlers.cartcontroler import *
from .controlers.paymentController import *
from werkzeug.security import check_password_hash
from flask_login import login_required, logout_user

auth = Blueprint('auth', __name__, template_folder='templates/')


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        customer = checkForCustomer(email)
        if 1 in customer:
            customer = getUser(email)
            if check_password_hash(customer.Password, password):
                flash('logged in succesfully', category='success')
                setLoginUser(customer)
                return redirect(url_for('views.shop'))
            else:
                flash('Inconrrect password, try again.', category='error')
        else:
            flash('Email does not ecist. ', category='error')
    return render_template('login.html')


@auth.route('/change-password')
def changePassword():
    return render_template('change_passLogin.html')


@auth.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        fname = request.form.get('fname')
        lname = request.form.get('lname')
        email = request.form.get('email')
        pass1 = request.form.get('pass1')
        pass2 = request.form.get('pass2')

        customer = checkForCustomer(email)
        if 1 in customer:
            flash('Email already exist.', category='error')
        elif len(email) < 4:
            flash('Email must be graater than 3 characters.', category='error')
        elif len(fname) < 2:
            flash('fname must be graater than 1 characters.', category='error')
        elif pass1 != pass2:
            flash('passwords don\'t match.', category='error')
        elif len(pass1) < 5:
            flash('password is to short.', category='error')
        else:
            CreateAccount(fname, lname, email, pass1)
            CreateCart()
            CreateCard()

            flash('Account created', category='success')
            return redirect(url_for('views.shop'))
    return render_template('register.html')


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

website/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import current_user, login_required
from .controlers.usercontroler import *
from .controlers.productsControler import *
from .controlers.ordersControler import *
from .controlers.cartcontroler import *
from .controlers.paymentController import *
from .controlers.profilecontroler import *

import json
import pprint

views = Blueprint('views', __name__, template_folder='templates/')


@views.route('/')
@views.route('/shop', methods=['GET', 'POST'])
def shop():
    telescopes = getAllTelescopes()
    brands = getAllBrands()
    price = [getMinPrice()[0], getMaxPrice()[0]]
    lens = getAllLensType()
    focal_distance = [getMinFocalDistance()[0], getMaxFocalDistance()[0]]
    aperture = [getMinAperture()[0], getMaxAperture()[0]]
    mounts = getAllMounts()
    cart = None
    cart_items = None
    total = 0

    if current_user.is_authenticated:
        cart = getCart()
        cart_items = json.loads(cart.items)
        total = float(cart.total_price)

    if request.method == 'POST':
        price = [request.form.get('minPrice'), request.form.get('maxPrice')]
        focal_distance = \
            [request.form.get('minFocal_distance'),
             request.form.get('maxFocal_distance')]
        aperture = [request.form.get('minAperture'),
                    request.form.get('maxAperture')]
        checkedBrands = request.form.getlist('brand')
        checkedLens = request.form.getlist('lens')
        checkedMount = request.form.getlist('mount')

        print(checkedBrands, checkedLens, checkedMount)

        if aperture[0] == '':
            aperture[0] = getMinAperture()[0]

        if aperture[1] == '':
            aperture[1] = getMaxAperture()[0]

        if focal_distance[0] == '':
            focal_distance[0] = getMinFocalDistance()[0]

        if focal_distance[1] == '':
            focal_distance[1] = getMaxFocalDistance()[0]

        if price[0] == '':
            price[0] = getMinPrice()[0]

        if price[1] == '':
            price[1] = getMaxPrice()[0]
        telescopes = filterTelesopes(price=price,
                                     focal_distance=focal_distance,
                                     aperture=aperture,
                                     brands=checkedBrands,
                                     lens=checkedLens,
                                     mounts=checkedMount)

    return render_template('shop.html', user=current_user,
                           telescopes=telescopes,
                           brands=brands,
                           price=price,
                           Lens=lens,
                           focal_distance=focal_distance,
                           aperture=aperture,
                           mounts=mounts,
                           cart=cart,
                           items=cart_items,
                           total=total)


@views.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    name = getCardName()
    number = getCardNumber()
    type = getCardType()
    month = getMonth()
    year = getYear()

    cart = getCart()
    cart_items = json.loads(cart.items)

    total = float(cart.total_price)

    if request.method == "POST":
        fname = request.form.get('fname')
        if fname == None:
            fname = current_user.Fname
        else:
            setFname(fname)

        lname = request.form.get('lname')
        if lname == None:
            lname = current_user.Lname
        else:
            setLname(lname)

        email = request.form.get('email')
        if email == None:
            email = current_user.Email
        else:
            setEmail(email)

        number = request.form.get('number')
        if number == None:
            number = current_user.Phone
        else:
            setNumber(number)

        aline1 = request.form.get('aline1')
        if aline1 == None:
            aline1 = current_user.Address
        else:
            setAline1(aline1)

        aline2 = request.form.get('aline2')
        if aline2 == None:
            aline2 = current_user.Street
        else:
            setAline2(aline2)

        city = request.form.get('city')
        if city == None:
            city = current_user.City
        else:
            setCity(city)

        state = request.form.get('state')
        if state == None:
            state = current_user.State
        else:
            setState(state)

        zipcode = request.form.get('zipcode')
        if zipcode == None:
            zipcode = current_user.ZipCode
        else:
            setZipCode(zipcode)

        cname = request.form.get('card_name')
        if cname == None:
            cname = getCardName()
        else:
            setCname(cname)

        ctype = request.form.get('card_type')
        if ctype == None:
            ctype = getCardType()
        else:
            setCtype(ctype)

        cnumber = request.form.get('card_num')
        if cnumber == None:
            cnumber = getCardNumber()
        else:
            setCnumber(cnumber)

        month = request.form.get('month')
        if month == None:
            month = getMonth()
        else:
            setMonth(month)

        year = request.form.get('year')
        if year == None:
            year = getYear()
        else:
            setYear(year)

        dataBase.session.commit()
        return redirect(url_for('views.profile'))

    return render_template('profile.html', user=current_user,
                           cart=cart,
                           items=cart_items,
                           name=name,
                           number=number,
                           type=type,
                           month=month,
                           year=year
                           )


@views.route('/orders', methods=['GET', 'POST'])
@login_required
def orders():

    Count = countORders()
    orders = getUserOrders()
    data = getOrderItems()

    cart = getCart()
    cart_items = json.dumps(cart.items)
    if cart_items == "NULL":
        cart_items = []
    # se debe cambiar al de las ordenes
    total = float(cart.total_price)

    total_items = len(cart_items)

    return render_template('orders.html', user=current_user,
                           item=cart_items,
                           cart=cart,
                           count=Count,
                           total_items=total_items,
                           orders=orders,
                           i=data)


@views.route('/checkout',  methods=['GET', 'POST'])
@login_required
def checkout():
    cart = None
    cart_items = None
    total_items = None

    cart = getCart()
    cart_items = json.loads(cart.items)
    total = float(cart.total_price)

    name = getCardName()
    number = getCardNumber()
    type = getCardType()
    month = getMonth()
    year = getYear()

    if request.method == "POST":
        fname = request.form.get('fname')
        if fname == None:
            fname = User.Fname
        else:
            setFname(fname)

        lname = request.form.get('lname')
        if lname == None:
            lname = User.Lname
        else:
            setLname(lname)

        email = request.form.get('email')
        if email == None:
            email = User.Email
        else:
            setEmail(email)

        number = request.form.get('number')
        if number == None:
            number = User.Phone
        else:
            setNumber(number)

        aline1 = request.form.get('aline1')
        if aline1 == None:
            aline1 = User.Address
        else:
            setAline1(aline1)

        aline2 = request.form.get('aline2')
        if aline2 == None:
            aline2 = User.Street
        else:
            setAline2(aline2)

        city = request.form.get('city')
        if city == None:
            city = User.City
        else:
            setCity(city)

        state = request.form.get('state')
        if state == None:
            state = User.State
        else:
            setState(state)

        zipcode = request.form.get('zipcode')
        if zipcode == None:
            zipcode = User.ZipCode
        else:
            setZipCode(zipcode)

        cname = request.form.get('card_name')
        if cname == None:
            cname = getCardName()
        else:
            setCname(cname)

        ctype = request.form.get('card_type')
        if ctype == None:
            ctype = getCardType()
        else:
            setCtype(ctype)

        cnumber = request.form.get('card_num')
        if cnumber == None:
            cnumber = getCardNumber
        else:
            setCnumber(cnumber)

        month = request.form.get('month')
        if month == None:
            month = getMonth()
        else:
            setMonth(month)

        year = request.form.get('year')
        if year == None:
            year = getYear()
        else:
            setYear(year)
        dataBase.session.commit()
        return redirect(url_for('views.checkout'))

    return render_template('checkout.html', user=current_user,
                           cart=cart,
                           items=cart_items,
                           total_items=total_items,
                           name=name,
                           number=number,
                           type=type,
                           month=month,
                           year=year,
                           total=total,
                           cart_items=cart_items)


@views.route('/invoice', methods=['GET', 'POST'])
@login_required
def invoice():

    result = create_order()
    prods = json.loads(json.loads(result.order_prods))
    # prods = getOrderItemsByNumber(result.tracking_num)

    cart = getCart()
    cart_items = json.loads(cart.items)
    total = float(cart.total_price)
    tracking_number = get_trackingnum()
    order_date = getOrderDate()
    total_amount = 100

website/templates/BaseClient.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <!--=====================================
                    META TAG PART START
        =======================================-->
    <!-- REQUIRE META -->
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- AUTHOR META -->
    <meta name="author" content="mironcoder" />
    <meta name="email" content="mironcoder@gmail.com" />
    <meta name="profile" content="https://themeforest.net/user/mironcoder" />

    <!-- TEMPLATE META -->
    <meta name="name" content="Nebula" />
    <meta name="title" content="Nebula - eCommerce HTML Template" />
    <meta
      name="keywords"
      content="telescopes, astrology, shop, ecommerce, store, html, bootstrap, template, webshop, online store"
    />
    <!--=====================================
                    META-TAG PART END
        =======================================-->

    <!-- WEBPAGE TITLE -->
    <title>{% block title %} {% endblock %}</title>

    <!--=====================================
                    CSS LINK PART START
        =======================================-->
    <!-- FAVICON -->
    <link rel="icon" href="{{url_for('static', filename='images/logo.png')}}" />

    <!-- FONTS -->
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='fonts/flaticon/flaticon.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='fonts/icofont/icofont.min.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='fonts/fontawesome/fontawesome.min.css')}}"
    />

    <!-- VENDOR -->
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='vendor/venobox/venobox.min.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='vendor/slickslider/slick.min.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='vendor/niceselect/nice-select.min.css')}}"
    />
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='vendor/bootstrap/bootstrap.min.css')}}"
    />

    <!-- CUSTOM -->
    <link
      rel="stylesheet"
      href="{{url_for('static', filename='css/main.css')}}"
    />

    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>
    <!--=====================================
                    CSS LINK PART END
        =======================================-->
  </head>
  <body ng-app="">
    <div class="backdrop"></div>
    <a class="backtop fas fa-arrow-up" href="#"></a>

    <!--=====================================
                    HEADER PART START
        =======================================-->

    <header class="header-part">
      <div class="container">
        <div class="header-content">
          <div class="header-media-group">
            <button class="header-user">
              <img src="static/images/user.png" alt="user" />
            </button>
            <a href="{{url_for('views.shop')}}"
              ><img src="static/images/logo.png" alt="logo"
            /></a>
            <button class="header-src"><i class="fas fa-search"></i></button>
          </div>

          <a href="{{url_for('views.shop')}}" class="header-logo">
            <img src="static/images/logo.png" alt="logo" />
          </a>

          {% if user.is_authenticated %}
          <ul class="dropdown">
            <a class="navbar-link dropdown-arrow" href="#">My Account</a>
            <ul class="dropdown-position-list">
              <li><a href="{{url_for('views.profile')}}">Account Info</a></li>
              <li><a href="{{url_for('views.orders')}}">My Orders</a></li>
              <li><a href="{{url_for('auth.logout')}}">Logout</a></li>
            </ul>
          </ul>
          {% else %}
          <ul class="dropdown">
            <a class="navbar-link" href="{{url_for('auth.login')}}">Login</a>
          </ul>
          {% endif %}

          <form class="header-form">
            <input type="text" placeholder="Search anything..." />
            <button><i class="fas fa-search"></i></button>
          </form>

          {% if user.is_authenticated %}
          <div class="header-widget-group">
            <button class="header-widget header-cart" title="Cartlist">
              <i class="fas fa-shopping-basket"></i>
              <sup> {{cart.total_items}} </sup>

              <span>total price<small>${{total}}0</small></span>
            </button>
          </div>
          {% endif %}
        </div>
      </div>
    </header>
    <!--=====================================
                    HEADER PART END
        =======================================-->

    <!--=====================================
                  CART SIDEBAR PART START
        =======================================-->
    <aside class="cart-sidebar">
      <div class="cart-header">
        <div class="cart-total">
          <i class="fas fa-shopping-basket"></i>
          <span>total item ({{cart.total_items}})</span>
        </div>
        <button class="cart-close"><i class="icofont-close"></i></button>
      </div>
      <ul class="cart-list">
        {% if user.is_authenticated %} {% for item in items %}
        <li class="cart-item">
          <div class="cart-media">
            <a href="#"
              ><img
                src="static/images/product-images/{{item['product']['image']}}"
                alt="product"
            /></a>
            <form
              action="{{url_for('views.deleteFromCart', itemid = item['product']['id'])}}"
            >
              <button class="cart-delete">
                <i class="far fa-trash-alt"></i>
              </button>
            </form>
          </div>
          <div class="cart-info-group">
            <div class="cart-info">
              <h6>
                <a href="product-single.html">{{item['product']['name']}}</a>
              </h6>
              <p>Unit Price - ${{item['product']['price']}}</p>
            </div>
            <form
              action="{{url_for('views.editItemInCart', itemid = item['product']['id'])}}"
              method="post"
            >
              <div class="cart-action-group">
                <div class="product-action">
                  <button class="action-minus" title="Quantity Minus">
                    <i class="icofont-minus"></i>
                  </button>
                  <input
                    class="action-input"
                    title="Quantity Number"
                    type="text"
                    name="quantity"
                    value="{{item['quantity']}}"
                  />
                  <button class="action-plus" title="Quantity Plus">
                    <i class="icofont-plus"></i>
                  </button>
                </div>

                <button class="action">Save</button>

                <h6>${{item['product']['price'] * item['quantity']}}</h6>
              </div>
            </form>
          </div>
        </li>
        {% endfor %} {% endif %}
      </ul>
      <div class="cart-footer">
        <a class="cart-checkout-btn" href="{{url_for('views.checkout')}}">
          <span class="checkout-label">Proceed to Checkout</span>
          <span class="checkout-price">${{total}}</span>
        </a>
      </div>
    </aside>
    <!--=====================================
                    CART SIDEBAR PART END
        =======================================-->

    <!--=====================================
                    BANNER PART START
        =======================================-->
    <section class="inner-section single-banner">
      <div class="container">
        <h2>Nebula</h2>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="#">Shop/</a></li>
        </ol>
      </div>
    </section>
    <!--=====================================
                    BANNER PART END
        =======================================-->

    {% block content %} {% endblock %}

    <!--=====================================
                     FOOTER PART START
        =======================================-->
    <footer class="footer-part">
      <div class="container">
        <div class="row">
          <div class="col-sm-6 col-xl-3">
            <div class="footer-widget">
              <a class="footer-logo" href="#">
                <img src="static/images/logo.png" alt="logo" />
              </a>
              <p class="footer-desc">
                This e-commerce template has been created for the sole purpose
                of aiding the students for the Databases course
              </p>
            </div>
          </div>
          <div class="col-sm-6 col-xl-3">
            <div class="footer-widget contact">
              <h3 class="footer-title">contact us</h3>
              <ul class="footer-contact">
                <li>
                  <i class="icofont-ui-email"></i>
                  <p>
                    <span>javier.quinones3@upr.edu</span>
                    <span>eliana.valenzuela@upr.edu</span>
                  </p>
                </li>
                <li>
                  <i class="icofont-ui-touch-phone"></i>
                  <p>
                    <span>+787 597 7369</span>
                    <span>N/A</span>
                  </p>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-sm-6 col-xl-3">
            <div class="footer-widget">
              <h3 class="footer-title">Quick Links</h3>
              <div class="footer-links">
                <ul>
                  <li>
                    <a href="https://github.com/CCOM-UPRA"
                      >Github original Template</a
                    >
                  </li>
                  <li>
                    <a href="https://github.com/Jean029/DataBaseProyect"
                      >Github Nebula Page</a
                    >
                  </li>
                  <li><a href="http://upra.edu/">upra.edu</a></li>
                  <li>
                    <a
                      href="https://cursos.upra.edu/course/search.php?areaids=core_course-course&q=ccom4115-ME5"
                      >cursos.upra.edu</a
                    >
                  </li>
                </ul>
                <ul>
                  <li>
                    <a href="https://www.youtube.com/watch?v=Z1RJmh_OqeA"
                      >Flask tutorial</a
                    >
                  </li>
                  <li>
                    <a href="https://www.youtube.com/watch?v=qz0aGYrrlhU"
                      >HTML tutorial</a
                    >
                  </li>
                  <li>
                    <a href="https://www.youtube.com/watch?v=kqtD5dpn9C8"
                      >Python tutorial</a
                    >
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-sm-6 col-xl-3">
            <div class="footer-widget">
              <h3 class="footer-title">Students of CCOM4115</h3>
              <p class="footer-desc">
                Do not hesitate to reach out to the professor or TA with any
                questions.
              </p>
            </div>
          </div>
        </div>
        <br />
      </div>
    </footer>
    <!--=====================================
                      FOOTER PART END
        =======================================-->

    <!--=====================================
                    JS LINK PART START
        =======================================-->
    <!-- VENDOR -->
    <script src="{{url_for('static', filename='vendor/bootstrap/jquery-1.12.4.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/bootstrap/popper.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/bootstrap/bootstrap.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/countdown/countdown.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/niceselect/nice-select.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/slickslider/slick.min.js')}}"></script>
    <script src="{{url_for('static', filename='vendor/venobox/venobox.min.js')}}"></script>

    <!-- CUSTOM -->
    <script src="{{url_for('static', filename='js/nice-select.js')}}"></script>
    <script src="{{url_for('static', filename='js/countdown.js')}}"></script>
    <script src="{{url_for('static', filename='js/accordion.js')}}"></script>
    <script src="{{url_for('static', filename='js/venobox.js')}}"></script>
    <script src="{{url_for('static', filename='js/slick.js')}}"></script>
    <script src="{{url_for('static', filename='js/main.js')}}"></script>

    <script>
      function myFunc(e) {
        e.preventDefault();
      }
    </script>

    <script>
      window.onload = function () {
        document.getElementById("submit").onclick = function () {
          document.getElementById("quantity").value =
            document.getElementById("quantity1").value;
        };
      };
    </script>

    <script>
      function onlyOne(checkbox) {
        var checkboxes = document.getElementsByName("check");
        checkboxes.forEach((item) => {
          if (item !== checkbox) item.checked = false;
        });
      }
    </script>
    <!--=====================================
                    JS LINK PART END
        =======================================-->
  </body>
</html>

website/templates/login.html
{% extends 'BaseClientLogin.html' %}

<!--A block is used to replace a part of a blueprint for othe information-->

<!--Here the title of the page is replaced-->
{% block title %}Login{% endblock %}

<!--And here is replaced the content, the names are not nesesari related to what is being replaced
is like having a variable, if is there no previus base information in the block in the blueprint
this information will be put there other wise this information will replace the information in the blueprint-->
{% block content %}
<!--=====================================
                USER FORM PART START
    =======================================-->
<section class="user-form-part">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-sm-10 col-md-12 col-lg-12 col-xl-10">
        <div class="user-form-logo">
          <a href="#"
            ><img
              src="{{url_for('static', filename='images/logo.png')}}"
              alt="logo"
          /></a>
        </div>
        <div class="user-form-card">
          <div class="user-form-title">
            <h2 class="SetTextColor">welcome!</h2>
            <p>Use your credentials to access</p>
          </div>

          <div style="padding: 0px 30%" class="user-form-group">
            <form class="user-form" method="POST">
              <div class="form-group">
                <input
                  type="email"
                  class="form-control"
                  name="email"
                  placeholder="Enter your email"
                />
              </div>
              <div class="form-group">
                <input
                  type="password"
                  class="form-control"
                  name="password"
                  placeholder="Enter your password"
                />
              </div>
              <div class="form-button">
                <button type="submit" class="SetBackgroundColor">login</button>
                <p>
                  Forgot your password?
                  <a href="#" class="SetTextColor"> reset here</a>
                </p>
              </div>
            </form>
          </div>
        </div>
        <div class="user-form-remind">
          <p>
            Don't have any account?<a
              href="{{url_for('auth.register')}}"
              class="SetTextColor"
              >register here</a
            >
          </p>
        </div>
        <div class="user-form-footer">
          <p>
            Nebula | &COPY; Copyright by
            <a href="#" class="SetTextColor">Mironcoder</a>
          </p>
        </div>
      </div>
    </div>
  </div>
</section>
<!--=====================================
                USER FORM PART END
    =======================================-->
{% endblock content %}

website/templates/register.html
{% extends 'BaseClientLogin.html' %} {% block title %}Register{% endblock title
%} {% block content %}

<!--=====================================
                USER FORM PART START
    =======================================-->
<section class="user-form-part">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 col-sm-10 col-md-12 col-lg-12 col-xl-10">
        <div class="user-form-logo">
          <a href="index.html"
            ><img
              src="{{url_for('static', filename='images/logo.png')}}"
              alt="logo"
          /></a>
        </div>
        <div class="user-form-card">
          <div class="user-form-title">
            <h2>welcome!</h2>
            <p>Use your credentials to access</p>
          </div>

          <div style="padding: 0px 30%" class="user-form-group">
            <form class="user-form" method="POST">
              <div class="form-group">
                <input
                  type="text"
                  class="form-control"
                  name="fname"
                  placeholder="Enter your first name"
                />
              </div>
              <div class="form-group">
                <input
                  type="text"
                  class="form-control"
                  name="lname"
                  placeholder="Enter your last name"
                />
              </div>
              <div class="form-group">
                <input
                  type="email"
                  class="form-control"
                  name="email"
                  placeholder="Enter your email"
                />
              </div>
              <div class="form-group">
                <input
                  type="password"
                  class="form-control"
                  name="pass1"
                  placeholder="Enter your password"
                />
              </div>
              <div class="form-group">
                <input
                  type="password"
                  class="form-control"
                  name="pass2"
                  placeholder="Enter your password again"
                />
              </div>
              <div class="form-button">
                <button type="submit">register</button>
              </div>
            </form>
          </div>
        </div>
        <div class="user-form-remind">
          <p>
            Have an account already?<a href="{{url_for('auth.login')}}"
              >return to login</a
            >
          </p>
        </div>
        <div class="user-form-footer">
          <p>Nebula | &COPY; Copyright by <a href="#">Mironcoder</a></p>
        </div>
      </div>
    </div>
  </div>
</section>
<!--=====================================
                USER FORM PART END
    =======================================-->

{% endblock content %}